### ISSUE TITLE
Investigate date-fns to replace moment

### ISSUE THREAD

**Issue by tivac** [tivac/anthracite#114]
Since moment & rollup aren't getting along

**Comment by voodoochild** [comment]
I've done the work to replace `moment` with `date-fns` on my fork but, like a dickhead, I forgot to branch first so can't open a pull request until my existing PR is merged.

The commit is here if you want to take an early peek: https://github.com/voodoochild/anthracite/commit/b66aa3c8958c2728eb6d2312905fe3edf3b29978

I haven't looked at changing the build process to use `rollup` since I figured that you might already have a branch for that.
